apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: helloprow-go-8lmf
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:f9a62642da55cb7d23687404464e727e49a5d6168eddff6b8acd02265a6b539c
        name: container-image
        resources: {}
status: {}
